# -*- coding: utf-8 -*-
"""Table_finetuning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cK5lNUtYUnULMO_8MNgZGmAVFUBK1Ry
"""

# 1. Ultralytics 설치
!pip install ultralytics

# 2. 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# 3. 라이브러리 임포트
import os
import yaml
import torch
from ultralytics import YOLO

# ─────────────────────────────────
# GPU 확인
# ─────────────────────────────────
print("=" * 40)
print(f"GPU 사용 가능: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU 이름: {torch.cuda.get_device_name(0)}")
else:
    print("경고: GPU 없음 → 런타임 유형 변경 필요")
print("=" * 40)

zip_path = '/content/drive/MyDrive/MimediQ_finetuning/Table_labeling.v1i.yolov8.zip'

# 압축 풀 경로
extract_path = '/content/datasets'

# 압축 해제 실행
if not os.path.exists(extract_path):
    os.makedirs(extract_path)
    !unzip -q "{zip_path}" -d "{extract_path}"
    print("압축 해제 완료!")

# ─────────────────────────────────
# data.yaml 경로 수정
# ─────────────────────────────────
yaml_file = os.path.join(extract_path, 'data.yaml')

with open(yaml_file, 'r') as f:
    data = yaml.safe_load(f)

data['train'] = os.path.join(extract_path, 'train/images')
data['val']   = os.path.join(extract_path, 'valid/images')
data['test']  = os.path.join(extract_path, 'test/images')

with open(yaml_file, 'w') as f:
    yaml.dump(data, f)

print("--- 수정된 data.yaml ---")
with open(yaml_file, 'r') as f:
    print(f.read())

# ─────────────────────────────────
# 모델 로드
# ─────────────────────────────────
model = YOLO('yolov8n.pt')

# ─────────────────────────────────
# 콜백: mAP50 목표 도달 시 조기 종료
# ─────────────────────────────────
def stop_at_target_map(trainer):
    current_map50 = trainer.metrics.get('metrics/mAP50(B)', 0)
    if current_map50 >= 0.80:
        print(f"\n[알림] 목표 mAP50 도달! (현재: {current_map50:.4f})")
        print("학습 조기 종료 후 최상의 모델 보존합니다.")
        trainer.stop = True

model.add_callback("on_train_epoch_end", stop_at_target_map)

# ─────────────────────────────────
# 학습 시작
# ─────────────────────────────────
model.train(
    data=yaml_file,
    epochs=100,
    imgsz=640,
    batch=16,
    patience=30,
    device=0,
    lr0=0.01,
    lrf=0.01,
    warmup_epochs=3,
    save_period=10,
    project="/content/drive/MyDrive/MimediQ",
    name="nutrition_table",
)

# ─────────────────────────────────
# 학습 결과 확인
# ─────────────────────────────────
print("\n" + "=" * 40)
print("학습 완료 - 최종 성능")
print("=" * 40)
results = model.val()

print(f"mAP50:     {results.box.map50:.3f}")
print(f"mAP50-95:  {results.box.map:.3f}")
print(f"Precision: {results.box.mp:.3f}")
print(f"Recall:    {results.box.mr:.3f}")

class_names = model.names
print("\n" + "=" * 40)
print("클래스별 상세 성능")
print("=" * 40)
print(f"{'클래스':<20} | {'Precision':>9} {'Recall':>6} {'mAP50':>6}")
print("-" * 48)
for i, name in enumerate(class_names.values()):
    p     = results.box.p[i]
    r     = results.box.r[i]
    map50 = results.box.maps[i]
    print(f"{name:<20} | {p:>9.3f} {r:>6.3f} {map50:>6.3f}")

# ─────────────────────────────────
# nutrition_best.pt 로 저장
# ─────────────────────────────────
import shutil
from pathlib import Path

best_pt = "/content/drive/MyDrive/MimediQ/nutrition_table/weights/best.pt"
dst_pt  = "/content/drive/MyDrive/MimediQ/nutrition_best.pt"

if Path(best_pt).exists():
    shutil.copy(best_pt, dst_pt)
    print(f"\n모델 저장 완료: {dst_pt}")
else:
    print(f"\n⚠️ best.pt 없음 - 경로 확인: {best_pt}")